server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /demo
  port: 8081
  connection-timeout: 5000ms
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tiangong?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: tiangong-spring-boot-demo
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true
    session:
      store-type: redis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: AUTO

tiangong:
  security:
    noAuthPaths: ["/index.html"]
    loginUrl: /login
    tokenExpiredTime: 300
  swagger:
    enable: true
    contact:
      name: godric
      url: http://miaochen.wang
      email: miaochengod@outlook.com


logging:
  level:
    root: info
  path: logs/
  file: tiangong-spring-boot-demo.log
