eureka:
  instance:
    prefer-ip-address: true
    metadata-map.management.context-path: ${server.servlet.context-path}/actuator
  #    health-check-url-path: ${server.servlet.context-path}/actuator/health
  #    status-page-url-path: ${server.servlet.context-path}/actuator/info
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://registry:8761/eureka/,http://registry1:8762/eureka/

#请求处理的超时时间
ribbon:
  ReadTimeout: 12000
  #请求连接的超时时间
  ConnectTimeout: 5000

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

spring:
  main:
    allow-bean-definition-overriding: true