create sequence hibernate_sequence start with 1 increment by 1;
create table tiangong_rbac_dept (id bigint not null, createdBy varchar(255), createdDate timestamp, updatedBy varchar(255), updatedDate timestamp, yn integer, name varchar(255), orderNum integer, parent_id bigint, primary key (id));
create table tiangong_rbac_menu (id bigint not null, createdBy varchar(255), createdDate timestamp, updatedBy varchar(255), updatedDate timestamp, yn integer, icon varchar(255), name varchar(255), orderNum integer, type integer, url varchar(255), visible integer, parent_id bigint, primary key (id));
create table tiangong_rbac_menu_resource (menu_id bigint not null, resource_id bigint not null);
create table tiangong_rbac_recource (id bigint not null, createdBy varchar(255), createdDate timestamp, updatedBy varchar(255), updatedDate timestamp, yn integer, method varchar(255), name varchar(255), path varchar(255), remark varchar(255), tag varchar(255), primary key (id));
create table tiangong_rbac_role (id bigint not null, createdBy varchar(255), createdDate timestamp, updatedBy varchar(255), updatedDate timestamp, yn integer, name varchar(255), remark varchar(255), primary key (id));
create table tiangong_rbac_role_menu (role_id bigint not null, menu_id bigint not null);
create table tiangong_rbac_user (id bigint not null, createdBy varchar(255), createdDate timestamp, updatedBy varchar(255), updatedDate timestamp, yn integer, email varchar(255), lockedTime timestamp, mobile varchar(255), password varchar(255), realName varchar(255), salt varchar(255), status integer, triedTimes integer, username varchar(255), dept_id bigint, primary key (id));
create table tiangong_rbac_user_role (user_id bigint not null, role_id bigint not null);
alter table tiangong_rbac_role add constraint UKc3lca40hth3yhq66g61i17hl3 unique (name);
alter table tiangong_rbac_user add constraint UKk9atv6i7ojeo4u85q38co9r5f unique (username);
alter table tiangong_rbac_dept add constraint FKo58jbcrpw6rsjkoxt5knmt565 foreign key (parent_id) references tiangong_rbac_dept;
alter table tiangong_rbac_menu add constraint FK7nby45oypdnbhc8flo6kqw6k0 foreign key (parent_id) references tiangong_rbac_menu;
alter table tiangong_rbac_menu_resource add constraint FKmvr93urv9kg7ydw7uebt5r0h7 foreign key (resource_id) references tiangong_rbac_recource;
alter table tiangong_rbac_menu_resource add constraint FKpqjxb6pngsgneeogkafc3j100 foreign key (menu_id) references tiangong_rbac_menu;
alter table tiangong_rbac_role_menu add constraint FK1u676nglp1heceywio6jc07gk foreign key (menu_id) references tiangong_rbac_menu;
alter table tiangong_rbac_role_menu add constraint FKfy6v1r7ms8cegp6c69r36iphx foreign key (role_id) references tiangong_rbac_role;
alter table tiangong_rbac_user add constraint FKmbgasqne1hy9cdk71cstb2uyb foreign key (dept_id) references tiangong_rbac_dept;
alter table tiangong_rbac_user_role add constraint FKpkfxyvlox4qaf51lphkwpuww7 foreign key (role_id) references tiangong_rbac_role;
alter table tiangong_rbac_user_role add constraint FKkbksxa2vhxrhwf6oynqxrsce4 foreign key (user_id) references tiangong_rbac_user;