spring:
  application:
    name: ironman
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD:testpassword}
      username: user
      profile: dev

  main:
    allow-bean-definition-overriding: true